// internal/check/integrity.go
//
// Comparison of what a package RECORDS against what was OBSERVED on disk.
//
// Nothing in this file performs I/O. tier.go does the observing -- one confined
// open per path, every question asked of that one descriptor -- and hands the
// result here as data, so every rule below is a pure function of (record,
// observation) and can be exercised on hostile shapes without a filesystem
// (INV-4).
//
// `pacman -Qkk` already verifies installed files against these same digests and
// already exempts %BACKUP%. None of that is presented as new. What this file
// adds is structure: findings carry evidence and stated limits, refusals are
// coverage gaps attributed to one subject rather than lines on stderr, the
// result is correlation input for the surfaces and provenance checks, and the
// digests come from an mtree the P4 baseline can itself hash -- which is how
// tampering with the mtree, invisible to -Qkk by construction, becomes
// detectable.
//
// Severity policy, decided deliberately: NO rule in this file reaches
// SevCritical. A digest mismatch, a moved link target or an unowned setuid bit
// cannot distinguish tampering from a local rebuild, an administrator's edit,
// or a pacman hook whose output this lane failed to derive. Reporting any of
// them as critical would put the tool's loudest severity on its least
// conclusive evidence, and a rule that fires on ordinary systems trains its
// user to ignore the tool. Critical stays with the definitive rules; the
// actionable form of these findings is the correlated one (P1-C) and the
// baseline-diffed one (P4).
package check

import (
	"fmt"
	"sort"

	"github.com/lookatitude/aurvet/internal/finding"
	"github.com/lookatitude/aurvet/internal/mtree"
)

// ObsKind says what an observation actually established. It exists so that
// "hashed and equal" can never be confused with "not read", which is the
// distinction INV-3 turns on.
type ObsKind int

const (
	// ObsHashed: the descriptor was read end to end and SHA256 is that read.
	ObsHashed ObsKind = iota

	// ObsMetadataOnly: the descriptor was opened and fstat'd, and nothing was
	// read. Size and Mode are from that fstat. Any verdict resting on this is
	// stat-only and must say so.
	ObsMetadataOnly

	// ObsLink: the path is a symlink and Link is its recorded-form target,
	// read but NOT resolved.
	ObsLink

	// ObsMissing: the path is not there. An observed absence, not a refusal.
	ObsMissing

	// ObsUnreadable: the path could not be examined coherently -- refused as a
	// symlink or a non-regular file, unreadable, or mutated mid-scan. Err
	// carries the refusal. Always a gap (INV-9), never a finding.
	ObsUnreadable

	// ObsExempt: deliberately not examined, because the derived exemption set
	// says pacman itself rewrites this file.
	ObsExempt
)

// Observed is one path as tier.Verify found it. Every field comes from the
// single descriptor that one confined open produced.
type Observed struct {
	Path   string
	Kind   ObsKind
	SHA256 string
	Mode   uint32 // st.Mode&0o7777, comparable with mtree.Entry.Mode
	Size   int64
	Link   string
	Err    error

	// StatOnly records that this path was opened and fstat'd but never read, so
	// a finding derived from it can say what it does and does not rest on
	// (INV-6). The triage and meta tiers set it; full and paranoid never do.
	//
	// It was called MtimeAssisted, after spec §13's description of triage as a
	// "stat prefilter" that hashes only mismatches -- a design in which mtime
	// decided what to read. Triage is no longer that: its hash set is decided in
	// phase 1 from the descriptor's own mode, because after the capability drop
	// the process cannot read a root-only file at all. **Nothing in this tree
	// consults mtime in any decision.** The old name, and the limits text that
	// went with it, told an operator a verdict rested on a timestamp that was
	// never looked at -- which is the manufactured confidence this project
	// exists to refuse, in the one place whose whole job is stating limits
	// honestly.
	StatOnly bool

	// Gapped records that phase 1 already raised a coverage gap naming this
	// path. Integrity then consumes that gap instead of raising a second one:
	// two true statements about one shortfall is still one shortfall, and the
	// duplication is the sort of inflation the INV-8 gate exists to catch.
	Gapped bool
}

const (
	limitDigest = "A content difference is not by itself compromise: a local rebuild, an administrator's edit, " +
		"and a file regenerated by a pacman hook this scan did not derive all look identical here. " +
		"Says nothing about whether the recorded digest is itself authentic -- that is what a signed baseline is for."
	limitLink = "The recorded target is compared as a string and is never resolved, so this says nothing about " +
		"where either target actually leads. An administrator's relink looks the same."
	limitMissing = "An absent packaged file is ordinary on systems where documentation, locales or headers were " +
		"deleted. Does not establish tampering, and does not establish that anything replaced it."
	limitSUID = "Not compromise on its own: locally built or vendor-installed software legitimately ships setuid " +
		"helpers. Ownership was resolved from the package database only -- a file owned by a package this scan " +
		"could not read would appear unowned here. THE SWEEP IS NOT A FULL SWEEP, and its blindness is the more " +
		"important limit: it covers usr, etc, opt, boot and srv minus the collector's skip list, which excludes " +
		"home, root, media, mnt, tmp, var/tmp and var/cache. A setuid binary planted in /tmp or in a user's home " +
		"is invisible to this rule at every tier, including paranoid. It also runs at tier paranoid only, so a " +
		"scan at any other tier says nothing at all about unowned setuid files."
	limitStatOnly = "The contents were never read: this rests on the size and mode from the descriptor's own " +
		"fstat, both of which anyone who can write the file can also set, and a change that preserves both is " +
		"invisible here. No timestamp was consulted. Re-run at tier full to hash it."
)

// Integrity compares one package's mtree records against the observations
// tier.Verify produced for them.
//
// pkg names the package, and is the subject the per-package coverage gap is
// attributed to. Findings are per PATH, and the path is the fingerprint subject
// precisely because it is version-independent (finding.Fingerprint's contract).
//
// t is the tier the observations were gathered at. It changes only two things:
// how a not-hashed observation is accounted for, and whether an exempt path's
// mismatch is reported at all.
func Integrity(pkg string, entries []mtree.Entry, obs map[string]Observed, ex Exemptions, t Tier) finding.Result {
	var res finding.Result
	var checkable, notHashed int

	for _, e := range entries {
		if e.Type == "dir" {
			// A directory carries no digest and no target. Its mode is not
			// checked here: mtree records the mode a package shipped, and
			// directory modes are legitimately shared and adjusted by several
			// packages and by systemd-tmpfiles.
			continue
		}
		checkable++

		o, ok := obs[e.Path]
		if !ok {
			// Not examined at all. Whatever the reason, the package cannot be
			// reported clean for this path.
			res.Gaps = append(res.Gaps, finding.Gap{
				RuleID: ruleForEntry(e), Subject: e.Path,
				Reason: fmt.Sprintf("package %s records this path but the scan produced no observation "+
					"for it; it was not examined", pkg),
			})
			continue
		}

		switch o.Kind {
		case ObsExempt:
			// Deliberately unexamined, and enumerable: Exemptions.All() is what
			// the report prints so this hole can be read rather than trusted.
			continue

		case ObsUnreadable:
			if o.Gapped {
				// The collector already reported this exact shortfall against
				// this exact subject. Saying it again under a second rule ID
				// inflates the gap count without adding a fact.
				continue
			}
			res.Gaps = append(res.Gaps, finding.Gap{
				RuleID: ruleForEntry(e), Subject: e.Path,
				Reason: fmt.Sprintf("could not be examined: %v", o.Err),
			})
			continue

		case ObsMissing:
			res.Findings = append(res.Findings, finding.Finding{
				RuleID: "integrity-missing", SubjectKind: "file", Subject: e.Path,
				Severity: finding.SevInfo,
				Summary:  "packaged file is not present on disk",
				Evidence: []string{"package=" + pkg, "recorded type=" + e.Type},
				Limits:   limitMissing,
			})
			continue

		case ObsLink:
			if e.Type != "link" {
				// The record says regular file, the observation says symlink.
				// We refuse to hash through it and we did not resolve it, so we
				// cannot say what it now is -- a gap, with the disagreement
				// stated.
				res.Gaps = append(res.Gaps, finding.Gap{
					RuleID: "integrity-digest-mismatch", Subject: e.Path,
					Reason: fmt.Sprintf("package %s records type=%s but the path is a symlink; refused "+
						"unresolved, so its contents were not verified", pkg, e.Type),
				})
				continue
			}
			if e.Link == "" {
				res.Gaps = append(res.Gaps, finding.Gap{
					RuleID: "integrity-link-target", Subject: e.Path,
					Reason: fmt.Sprintf("package %s records a symlink with no link= target; there is "+
						"nothing to compare the on-disk target against", pkg),
				})
				continue
			}
			if e.Link != o.Link {
				res.Findings = append(res.Findings, linkFinding(pkg, e, o))
			}
			continue
		}

		// From here the record must be a regular file with a digest.
		if e.Type == "link" {
			res.Gaps = append(res.Gaps, finding.Gap{
				RuleID: "integrity-link-target", Subject: e.Path,
				Reason: fmt.Sprintf("package %s records a symlink but the path was observed as a regular "+
					"file; the recorded target had nothing to compare against", pkg),
			})
			continue
		}
		if e.SHA256 == "" {
			// Includes the md5digest-only records (237 on the reference
			// system). An unverifiable record is a gap, never a pass: md5 is
			// not used here, so claiming coverage would be claiming a check
			// that did not run.
			res.Gaps = append(res.Gaps, finding.Gap{
				RuleID: "integrity-digest-mismatch", Subject: e.Path,
				Reason: fmt.Sprintf("package %s records no sha256 for this path (md5=%q); its contents "+
					"were not verified", pkg, e.MD5),
			})
			continue
		}

		switch o.Kind {
		case ObsHashed:
			if o.SHA256 == e.SHA256 {
				continue
			}
			res.Findings = append(res.Findings, digestFinding(pkg, e, o, ex, t))

		case ObsMetadataOnly:
			notHashed++
			// Metadata alone can only ever contradict the record, never confirm
			// it. A size disagreement is worth reporting; equality is not
			// evidence of anything and is accounted for in the coverage gap
			// below.
			if o.Size != e.Size {
				res.Findings = append(res.Findings, digestFinding(pkg, e, o, ex, t))
			}
		}
	}

	if notHashed > 0 {
		reason := fmt.Sprintf("%d of %d recorded paths were verified by metadata only and never hashed "+
			"(stat-only, tier %s); size and mode are both writable by anyone who can write the file, so "+
			"those paths are not covered by this run", notHashed, checkable, t)
		if t == TierTriage {
			// The tier's limit stated where the operator meets it. A limit that
			// only appears in the source is a limit they never meet, and this
			// one is why `baseline init` refuses a triage-tier basis.
			reason += ". Tier triage hashes only what the descriptor's own mode says decides what runs, " +
				"plus the watched paths; a file outside that subset whose contents changed while its size " +
				"stayed the same is NOT detected at this tier whatever its mtime says. Re-run at tier full"
		}
		res.Gaps = append(res.Gaps, finding.Gap{RuleID: "integrity-coverage", Subject: pkg, Reason: reason})
	}
	return res
}

// linkFinding renders a link-target disagreement. Every such disagreement is
// reported at the same severity, whatever the record held.
//
// A /dev/null RECORD IS NOT DOWNGRADED, and this is a reversal (lead decision,
// 2026-08-05) of a downgrade this file briefly carried. The shape is real and
// measured: a package that records a symlink to /dev/null is shipping an inert
// placeholder that something else -- typically its own install scriptlet, which
// pacman runs and no hook declares -- repoints afterwards, and on the reference
// system (1,410 packages, 458,724 recorded entries) that accounted for 2 of the
// 4 total findings these checks produced, both benign: java-runtime-common's
// ./usr/lib/jvm/default and ./usr/lib/jvm/default-runtime, relinked by
// archlinux-java.
//
// It is reported anyway, at suspicious, for two reasons that outrank the noise:
//
//   - "/dev/null placeholder, therefore expected" is a rule keyed on a value
//     THE PACKAGE ITSELF WRITES. A hostile package can record link=/dev/null and
//     ship the link pointing anywhere it likes, and the downgrade would have
//     made that the quietest way to plant one. The alternatives-style
//     indirection is exactly the mechanism worth watching -- /usr/lib/jvm/default
//     decides which java runs.
//   - The benign population is TWO PATHS on a full desktop system. That is not
//     the volume that trains an operator to ignore output; the honest place to
//     absorb it is adjudication and the P4 baseline diff, which suppress a
//     known-and-accepted state without teaching the rule to lie.
//
// The placeholder is still NAMED in the evidence and explained in the limits, so
// a reader sees the benign explanation next to the finding rather than instead of
// it (INV-6).
func linkFinding(pkg string, e mtree.Entry, o Observed) finding.Finding {
	f := finding.Finding{
		RuleID: "integrity-link-target", SubjectKind: "file", Subject: e.Path,
		Severity: finding.SevSuspicious,
		Summary:  "symlink does not point where the package recorded",
		Evidence: []string{
			"package=" + pkg,
			"recorded link=" + e.Link,
			"observed link=" + o.Link,
		},
		Limits: limitLink,
	}
	if e.Link == "/dev/null" {
		f.Summary = "symlink recorded as an inert /dev/null placeholder now points somewhere"
		f.Evidence = append(f.Evidence, "recorded target is the /dev/null placeholder")
		f.Limits = "Alternatives-style links look like this legitimately: the package ships an inert placeholder " +
			"and its own install scriptlet repoints it, which no pacman hook declares and this scan therefore " +
			"cannot derive (measured: java-runtime-common on an ordinary system). Not downgraded on that account -- " +
			"the recorded target is a field the package itself writes, so a package could record the placeholder " +
			"and ship the link pointing anywhere. " + limitLink
	}
	return f
}

// digestFinding renders a content disagreement, at the strength the
// observation actually supports.
func digestFinding(pkg string, e mtree.Entry, o Observed, ex Exemptions, t Tier) finding.Finding {
	f := finding.Finding{
		RuleID: "integrity-digest-mismatch", SubjectKind: "file", Subject: e.Path,
		Severity: finding.SevSuspicious,
		Summary:  "installed file does not match the digest its package recorded",
		Evidence: []string{"package=" + pkg},
		Limits:   limitDigest,
	}
	if o.Kind == ObsHashed {
		f.Evidence = append(f.Evidence,
			"recorded sha256="+e.SHA256, "observed sha256="+o.SHA256,
			fmt.Sprintf("recorded size=%d observed size=%d", e.Size, o.Size))
	} else {
		f.Summary = "installed file's size does not match the size its package recorded"
		f.Evidence = append(f.Evidence,
			fmt.Sprintf("recorded size=%d observed size=%d", e.Size, o.Size),
			"contents not hashed")
	}
	if o.StatOnly {
		// A terse marker; limitStatOnly carries what it means. The evidence list
		// is scanned by eye and by grep, so the token stays short and stable.
		f.Evidence = append(f.Evidence, "stat-only")
		f.Limits = limitStatOnly + " " + f.Limits
	}
	// Paranoid re-examines exempt paths. Such a mismatch is expected by
	// construction -- pacman regenerates the file -- so it is reported at info
	// with the exemption it overrode named, rather than suppressed (so the
	// exemption itself can be audited) and rather than raised (so it does not
	// become the noise the exemption exists to prevent).
	if x, ok := ex.Applies(e); ok && t == TierParanoid {
		f.Severity = finding.SevInfo
		f.Evidence = append(f.Evidence, "exempt: "+x.Reason, "exemption source="+x.Source)
		f.Limits = "Expected: this path is on the derived exemption list and is only checked at tier paranoid. " + f.Limits
	}
	return f
}

// ruleForEntry picks the rule a refusal is attributed to, so a gap lands under
// the check that did not run rather than under a generic bucket.
func ruleForEntry(e mtree.Entry) string {
	if e.Type == "link" {
		return "integrity-link-target"
	}
	return "integrity-digest-mismatch"
}

// SUIDFile is one setuid or setgid file found on disk, with the package that
// owns it if the caller's ownership oracle knew one.
//
// The oracle is the caller's (P1-C's ownership index): this function takes its
// answer as data so the rule stays a pure comparison, and so an oracle that
// could not answer is visible to the caller rather than swallowed here.
type SUIDFile struct {
	Path  string
	Mode  uint32
	Owner string
}

// UnownedSUID reports setuid/setgid files that no package claims.
//
// A package-owned setuid binary is ordinary (sudo, ping, mount, and their
// digests are checked by Integrity above). One that no package owns was put
// there by something else, which is worth a look and is not by itself
// compromise -- hence suspicious, with the ownership caveat stated.
//
// THIS RULE IS TIER PARANOID ONLY, said here because a declared rule that fires
// only at a non-default tier is otherwise indistinguishable from one that never
// fires -- and that has already bitten this project once. Its input is the
// metadata-only sweep of the watched trees, which spec §13 assigns to paranoid
// and to no other tier; at meta, triage and full this function is called with
// nothing and correctly reports nothing.
//
// Measured on the reference system: 33 setuid/setgid regular files, all inside
// the swept trees, all package-owned, so the rule produces zero findings there.
// That is the right baseline for a suspicious-severity rule -- any occurrence is
// damning -- and it is also why the sweep's blindness is stated in limitSUID
// rather than left to be discovered.
func UnownedSUID(files []SUIDFile) finding.Result {
	var res finding.Result
	sorted := append([]SUIDFile(nil), files...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Path < sorted[j].Path })
	for _, f := range sorted {
		if f.Mode&0o6000 == 0 || f.Owner != "" {
			continue
		}
		res.Findings = append(res.Findings, finding.Finding{
			RuleID: "integrity-unowned-setuid", SubjectKind: "file", Subject: f.Path,
			Severity: finding.SevSuspicious,
			Summary:  "setuid/setgid file is owned by no installed package",
			Evidence: []string{
				fmt.Sprintf("mode=%o", f.Mode),
				"no package in the local database claims this path",
			},
			Limits: limitSUID,
		})
	}
	return res
}
